# Generated by Django 5.1.1 on 2024-09-13 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fruits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_time', models.DateTimeField(auto_now_add=True)),
                ('total_purchase', models.FloatField(default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('fruit_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruits.fruits')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salles.order')),
            ],
        ),
    ]
