# Generated by Django 5.1.1 on 2024-09-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salles', '0002_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.AddField(
            model_name='sales',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
