# Generated by Django 5.1.1 on 2024-09-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('classification', models.CharField(choices=[('EX', 'Extra'), ('1ST', 'De primeira'), ('2ND', 'De segunda'), ('3RD', 'De terceira')], max_length=3)),
                ('fresh_fruits', models.CharField(choices=[('Y', 'Sim'), ('N', 'Não')], max_length=1)),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
